Repository steve1316/uma-android-automation, pull requests merged in 2025-08, with the labels that each got.

#26 Crash fix for concurrent modification during Training process
  README.md
  app/build.gradle
  app/src/main/java/com/steve1316/uma_android_automation/ui/settings/TrainingFragment.kt
  app/src/main/java/com/steve1316/uma_android_automation/utils/ImageUtils.kt
  app/src/main/res/xml/preferences_training.xml
  app/update.xml
Labels: bug

#33 Instructions for changing phone's resolution to 1080p
  README.md
Labels: documentation

#34 Redoes gradle definitions for one-click compile and more modern defaults.
  app/build.gradle
  app/build.gradle.kts
  app/proguard-rules.pro
  build.gradle
  build.gradle.kts
  gradle.properties
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.properties
  settings.gradle
  settings.gradle.kts
Labels: documentation, enhancement
